version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: qanounia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-49Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
  backend:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ../apps/backend/.env.example
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/qanounia
    depends_on:
      - postgres
      - redis
    ports:
      - '4000:4000'
  frontend:
    build:
      context: ..
      dockerfile: apps/frontend/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend
    ports:
      - '3000:3000'
volumes:
  postgres-data:
  minio-data:
