image:
  repository: ghcr.io/qanounia/backend
  tag: latest

frontendImage:
  repository: ghcr.io/qanounia/frontend
  tag: latest

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}
