apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qanounia.fullname" . }}-frontend
  labels: {{- include "qanounia.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "qanounia.name" . }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "qanounia.name" . }}-frontend
        {{- include "qanounia.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          resources: {{- toYaml .Values.resources | nindent 12 }}
